source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, "9.0"
target 'MWPhotoBrowser_Example'  do
  pod 'MWPhotoBrowser', :path => '../'
  pod 'SDWebImage' , '4.0.0'
end

target 'MWPhotoBrowser_Tests' do
  pod 'MWPhotoBrowser', :path => '../'

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
